### ISSUE TITLE
Give credit to Deivu

### ISSUE THREAD

**Issue by Luke-6723** [meister03/discord-cross-ratelimit#1]
I think some credit is due considering you literally copied their project.

![Image](https://img.pyrocdn.com/b9rndnEV.png)

**Comment by Luke-6723** [comment]
"heavily inspired" when you literally took the code :/

**Comment by meister03** [comment]
@Luke-6723 thx for reporting your concerns.
2. The Structure has been copied from Djs on both libraries
3. There is a License attached from the Owner Deivu and it is linked in the readme
"Credits goes to Azuma"
Considering checking the changes.md
