### ISSUE TITLE
 TypeError: this.initializeShardData is not a function

### ISSUE THREAD

**Issue by FxckingAngel** [meister03/discord-cross-ratelimit#2]
/var/lib/pterodactyl/volumes/6ac16c7b-e59f-4356-8929-88fac63dfbbc/node_modules/discord-cross-hosting/src/Managers/Server.js:121
            if (!this.standAlone) this.initializeShardData();
                                       ^

TypeError: this.initializeShardData is not a function
    at Timeout._onTimeout (/var/lib/pterodactyl/volumes/6ac16c7b-e59f-4356-8929-88fac63dfbbc/node_modules/discord-cross-hosting/src/Managers/Server.js:121:40)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by meister03** [comment]
Use the master branch, did not had the time yet, publishing it on npm

**Comment by meister03** [comment]
Give me 2 minutes pls

**Comment by meister03** [comment]
@FxckingAngel should be fixed, you have to uninstall and reinstall discord-cross-hosting

**Comment by FxckingAngel** [comment]
Ok

**Comment by FxckingAngel** [comment]
And my bot commands won't response like nothing but all the shards are on

**Comment by FxckingAngel** [comment]
all it does is
[Bridge] [READY] Bridge operational on :::4444
Server is ready:::4444
[Bridge] Created shardClusterList: [[[0],[1],[2],[3]]]
[Bridge => CM] [SHARDLIST_DATA_UPDATE][0] To all connected Clients
[]
[]

**Comment by meister03** [comment]
Could you show your cluster.js file?

**Comment by FxckingAngel** [comment]
const { Client } = require('discord-cross-hosting');
const Cluster = require('discord-hybrid-sharding');

const client = new Client({
    agent: 'bot',
    host: 'localhost', // Domain without https
    port: 4444, // Proxy Connection (Replit) needs Port 443
    // handshake: true, When Replit or any other Proxy is used
    authToken: 'theauthtoken',
    rollingRestarts: false, // Enable, when bot should respawn when cluster list changes.
});
client.on('debug', console.log);
client.connect();

const manager = new Cluster.Manager(`${__dirname}/index.js`, { totalShards: 1, totalClusters: 'auto' }); // Some dummy Data
manager.on('clusterCreate', cluster => console.log(`Launched Cluster ${cluster.id}`));
manager.on('debug', console.log);

client.listen(manager);
client
    .requestShardData()
    .then(e => {
        if (!e) return;
        if (!e.shardList) return;
        manager.totalShards = e.totalShards;
        manager.totalClusters = e.shardList.length;
        manager.shardList = e.shardList;
        manager.clusterList = e.clusterList;
        manager.spawn({ timeout: -1 });
    })
    .catch(e => console.log(e));

**Comment by meister03** [comment]
1.Start your Bridge
2. Start the Cluster File

**Comment by FxckingAngel** [comment]
i did

**Comment by meister03** [comment]
Please re-open the issue, when its not fixed yet
